#!/bin/bash

# so we can use `$CONFIG`, `pubkey` and such
. ./bashrc

_ssh() {
  if [ ! -e "$HOME/.ssh/id_rsa.pub" ]; then
    echo "Looks like you don't have any SSH keys yet. Wanna create them now?"
    read answer
    if [ "$answer" == "yes" -o "$answer" == "y" ]; then
      echo "Usually just hit enter to accept all the defaults."
      ssh-keygen
      clear
      echo "Cut and paste (yes with the mouse) the following to your" | sol yellow
      echo "GitHub -> Settings -> SSH Keys:" | sol yellow
      echo
      pubkey
      echo
    fi
  fi
}

_links() {
  links="
  bash_completion.d
  bash_profile
  bashrc
  vim
  dircolors
  gitconfig
  "

  for i in $links; do 
    target=$HOME/.$i
    if [ -e $target ]; then
      mv $target ${target}.$tstamp
    fi
    ln -fs $CONFIG/$i $target 
  done
}

_git(){
  echo
  echo "Don't forget to change your settings in gitconfig:"
  echo
  cat gitconfig
  echo
}

#####################################################
_ssh
_links
_git
