#!/bin/sh

tstamp=`$HOME/repos/workspace/bin/tstamp`
work=$HOME/repos/workspace

links="
bash_completion.d
bash_profile
bashrc
vim
dircolors
gitconfig
"

for i in $links; do 
  target=$HOME/.$i
  if [ -e $target ]; then
    mv $target ${target}.$tstamp
  fi
  ln -s $work/$i $target 
done

ln -s $work/bin $HOME
ln -s $work/lib $HOME
